CREATE TABLE IF NOT EXISTS USUARIOS (
     ID uuid PRIMARY KEY,
     NOME VARCHAR(255) NOT NULL,
     DOCUMENTO VARCHAR(100) NOT NULL,
     EMAIL VARCHAR(100) NOT NULL,
     SENHA VARCHAR(100)  NOT NULL,
     TIPO_USUARIO VARCHAR(20) NOT NULL,
     CARTEIRA DECIMAL(10, 2) NOT NULL,
     DATA_CADASTRO TIMESTAMP NOT NULL,
     VERSION BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON USUARIOS (DOCUMENTO);

CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON USUARIOS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSFERENCIAS (
     ID uuid PRIMARY KEY,
     PAGADOR uuid,
     RECEBEDOR uuid,
     VALOR  DECIMAL(10, 2),
     DATA_CRIACAO TIMESTAMP,
     FOREIGN KEY (PAGADOR)
     REFERENCES USUARIOS (ID),
     FOREIGN KEY (RECEBEDOR)
     REFERENCES USUARIOS (ID)
);